package catalog

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	pfs "github.com/Padrosum/pmusic/internal/fs"
	"github.com/Padrosum/pmusic/internal/meta"
)

func TestQuoteGL(t *testing.T) {
	got := quoteGL(`a"b\c`)
	if got != `"a\"b\\c"` {
		t.Fatalf("quote = %s", got)
	}
}

func TestRenderUsesPathNotYol(t *testing.T) {
	src, stats := Render("/music", []*pfs.Folder{{
		Name: "Jazz",
		Path: "/music/Jazz",
		Tracks: []pfs.Track{
			{Name: "Kind of Blue", Path: "/music/Jazz/Kind of Blue.flac", Ext: ".flac"},
		},
	}}, func(string) meta.Meta {
		return meta.Meta{Title: `Kind "Blue"`, Artist: "Miles", Album: "Kind of Blue"}
	})
	if stats.Tracks != 1 || stats.Albums != 1 {
		t.Fatalf("stats = %+v", stats)
	}
	text := string(src)
	if strings.Contains(text, "yol =") {
		t.Fatal("generated catalog used reserved yol field")
	}
	if !strings.Contains(text, `path = "Jazz/Kind of Blue.flac"`) {
		t.Fatalf("missing relative path:\n%s", text)
	}
	if !strings.Contains(text, `baslik = "Kind \"Blue\""`) {
		t.Fatalf("title not escaped:\n%s", text)
	}
	if !strings.Contains(text, "album = @album_1") {
		t.Fatalf("missing album ref:\n%s", text)
	}
}

func TestWriteFromScanReplacesSample(t *testing.T) {
	root := t.TempDir()
	music := filepath.Join(root, "music")
	if err := os.MkdirAll(filepath.Join(music, "A"), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(music, "A", "song.mp3"), []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	dest := filepath.Join(root, "library.gl")
	if err := os.WriteFile(dest, []byte("path = \"Gece/ilk-isik.flac\"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	stats, err := WriteFromScan(WriteOptions{MusicDir: music, Dest: dest, Meta: func(string) meta.Meta {
		return meta.Meta{Title: "Song"}
	}})
	if err != nil {
		t.Fatal(err)
	}
	if stats.Tracks != 1 {
		t.Fatalf("tracks = %d", stats.Tracks)
	}
	got, err := os.ReadFile(dest)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), `path = "A/song.mp3"`) {
		t.Fatalf("wrote:\n%s", got)
	}
}

func TestWriteFromScanRequiresForceForCustom(t *testing.T) {
	root := t.TempDir()
	music := filepath.Join(root, "music")
	if err := os.MkdirAll(music, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(music, "a.mp3"), []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	dest := filepath.Join(root, "library.gl")
	if err := os.WriteFile(dest, []byte("cins T\nveri mine : T { x = 1 }\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	_, err := WriteFromScan(WriteOptions{MusicDir: music, Dest: dest})
	if err == nil || !strings.Contains(err.Error(), "--force") {
		t.Fatalf("err = %v", err)
	}
	got, _ := os.ReadFile(dest)
	if string(got) != "cins T\nveri mine : T { x = 1 }\n" {
		t.Fatalf("custom catalog overwritten: %q", got)
	}
	if _, err := WriteFromScan(WriteOptions{MusicDir: music, Dest: dest, Force: true}); err != nil {
		t.Fatal(err)
	}
}

func TestWriteFromScanReplacesGenerated(t *testing.T) {
	root := t.TempDir()
	music := filepath.Join(root, "music")
	if err := os.MkdirAll(music, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(music, "a.mp3"), []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	dest := filepath.Join(root, "library.gl")
	if err := os.WriteFile(dest, []byte("# Generated by pmusic catalog from /old\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := WriteFromScan(WriteOptions{MusicDir: music, Dest: dest}); err != nil {
		t.Fatal(err)
	}
}

func TestWriteFromScanEmptyLibrary(t *testing.T) {
	_, err := WriteFromScan(WriteOptions{MusicDir: t.TempDir(), Dest: filepath.Join(t.TempDir(), "library.gl")})
	if err == nil || !strings.Contains(err.Error(), "no mp3/flac/wav") {
		t.Fatalf("err = %v", err)
	}
}

func TestRenderConvertsWithGenLang(t *testing.T) {
	if _, err := exec.LookPath("genlang"); err != nil {
		t.Skip("genlang not on PATH")
	}
	src, _ := Render("/music", []*pfs.Folder{{
		Name: "Jazz",
		Path: "/music/Jazz",
		Tracks: []pfs.Track{
			{Name: "So What", Path: "/music/Jazz/So What.flac", Ext: ".flac"},
		},
	}}, func(string) meta.Meta {
		return meta.Meta{Title: "So What", Artist: "Miles", Album: "Kind of Blue"}
	})
	path := filepath.Join(t.TempDir(), FileName)
	if err := os.WriteFile(path, src, 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := DefaultConverter().ConvertJSON(context.Background(), path); err != nil {
		t.Fatal(err)
	}
}
