package catalog

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	pfs "github.com/Padrosum/pmusic/internal/fs"
	"github.com/Padrosum/pmusic/internal/meta"
	"github.com/Padrosum/pmusic/internal/persistence"
)

// Stats is a summary of a generated library.gl file.
type Stats struct {
	Dest   string
	Tracks int
	Albums int
}

// WriteOptions control catalog generation from the local music directory.
type WriteOptions struct {
	MusicDir string
	Dest     string
	Force    bool
	Meta     func(path string) meta.Meta
}

// WriteFromScan scans musicDir and writes ~/.config/pmusic/library.gl
// (or Dest). The sample catalog and previously generated files may be
// replaced. A hand-edited catalog requires Force.
func WriteFromScan(opt WriteOptions) (Stats, error) {
	musicDir := strings.TrimSpace(opt.MusicDir)
	if musicDir == "" {
		return Stats{}, fmt.Errorf("music directory is empty")
	}
	root, err := pfs.Scan(musicDir)
	if err != nil {
		return Stats{}, err
	}
	folders := pfs.FlatFolders(root)
	readMeta := opt.Meta
	if readMeta == nil {
		readMeta = meta.Read
	}
	src, stats := Render(root.Path, folders, readMeta)
	if stats.Tracks == 0 {
		return Stats{}, fmt.Errorf("no mp3/flac/wav files in %s", musicDir)
	}
	dest := strings.TrimSpace(opt.Dest)
	if dest == "" {
		dir, err := configCatalogDir()
		if err != nil {
			return Stats{}, err
		}
		dest = filepath.Join(dir, FileName)
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o700); err != nil {
		return Stats{}, err
	}
	existing, err := os.ReadFile(dest)
	if err != nil && !os.IsNotExist(err) {
		return Stats{}, err
	}
	if err == nil && !opt.Force && !replaceableCatalog(existing) {
		return Stats{}, fmt.Errorf("%s already exists; pass --force to replace it", dest)
	}
	if err := persistence.WriteFileAtomic(dest, src, persistence.PrivateFileMode); err != nil {
		return Stats{}, err
	}
	stats.Dest = dest
	return stats, nil
}

func replaceableCatalog(existing []byte) bool {
	s := string(existing)
	return strings.Contains(s, "Generated by pmusic catalog") ||
		strings.Contains(s, "Gece/ilk-isik.flac")
}

// Render builds library.gl text from a scanned folder tree.
func Render(musicDir string, folders []*pfs.Folder, readMeta func(string) meta.Meta) ([]byte, Stats) {
	if readMeta == nil {
		readMeta = func(string) meta.Meta { return meta.Meta{} }
	}
	var albums []albumRow
	albumID := map[string]string{}
	var tracks []trackRow
	for _, folder := range folders {
		if folder == nil {
			continue
		}
		for _, track := range folder.Tracks {
			md := readMeta(track.Path)
			title := strings.TrimSpace(md.Title)
			if title == "" {
				title = track.Name
			}
			row := trackRow{
				ident:  fmt.Sprintf("parca_%d", len(tracks)+1),
				title:  title,
				artist: strings.TrimSpace(md.Artist),
				path:   relativeMusicPath(musicDir, track.Path),
			}
			albumTitle := strings.TrimSpace(md.Album)
			if albumTitle != "" {
				key := strings.ToLower(row.artist) + "\x00" + strings.ToLower(albumTitle)
				id, ok := albumID[key]
				if !ok {
					id = fmt.Sprintf("album_%d", len(albums)+1)
					albumID[key] = id
					albums = append(albums, albumRow{ident: id, title: albumTitle, artist: row.artist})
				}
				row.album = id
			}
			tracks = append(tracks, row)
		}
	}

	var b bytes.Buffer
	b.WriteString("# Generated by pmusic catalog from ")
	b.WriteString(quoteBare(musicDir))
	b.WriteString(".\n# File paths use `path`. Do not use `yol` (GenLang keyword).\n")
	b.WriteString("# Hand-edited kume / uye lines are replaced on the next generate unless you pass --force on a custom file.\n\n")
	b.WriteString("cins Medya {\n    baslik = \"\"\n}\n\n")
	b.WriteString("cins Ses -> Medya\n")
	b.WriteString("tur Album -> Ses\n")
	b.WriteString("tur Parca -> Ses {\n    sure_sn = 0\n    path = \"\"\n}\n\n")

	for _, album := range albums {
		fmt.Fprintf(&b, "veri %s : Album {\n    baslik = %s\n", album.ident, quoteGL(album.title))
		if album.artist != "" {
			fmt.Fprintf(&b, "    sanatci = %s\n", quoteGL(album.artist))
		}
		b.WriteString("}\n\n")
	}
	for _, track := range tracks {
		fmt.Fprintf(&b, "veri %s : Parca {\n    baslik = %s\n", track.ident, quoteGL(track.title))
		if track.artist != "" {
			fmt.Fprintf(&b, "    sanatci = %s\n", quoteGL(track.artist))
		}
		if track.album != "" {
			fmt.Fprintf(&b, "    album = @%s\n", track.album)
		}
		b.WriteString("    sure_sn = 0\n")
		fmt.Fprintf(&b, "    path = %s\n}\n\n", quoteGL(track.path))
	}

	return b.Bytes(), Stats{Tracks: len(tracks), Albums: len(albums)}
}

type albumRow struct {
	ident, title, artist string
}

type trackRow struct {
	ident, title, artist, album, path string
}

func relativeMusicPath(musicDir, trackPath string) string {
	if musicDir != "" {
		if rel, err := filepath.Rel(musicDir, trackPath); err == nil && rel != "." && !strings.HasPrefix(rel, "..") {
			return filepath.ToSlash(rel)
		}
	}
	return filepath.ToSlash(trackPath)
}

func quoteGL(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		case '\r':
			b.WriteString(`\r`)
		default:
			if r < 32 {
				b.WriteRune(' ')
				continue
			}
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func quoteBare(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "."
	}
	return s
}
